Add black beans and rice recipe
foundersandcoders/nazareth-recipes pull request #14
Opened 2017-07-28 11:32 UTC by ZooeyMiller

Added the black beans and rice recipe cooked this week
fix #12

2017-07-28 12:24 UTC, m4v15 requested changes
Add to folder, maybe change the title to include the peppers and onion stuff?

2017-07-28 12:24 UTC, m4v15 commented on README.md
> +[Black beans w/ Lime & Coriander rice (and sides)](black-beans.md)
Maybe put it in a recipes/mains/ folder, like mine?

2017-07-28 12:24 UTC, m4v15 commented on black-beans.md
> +# Black beans with lime and coriander rice
This seems more than just black beans and rice recipe?

2017-07-28 12:27 UTC, ZooeyMiller commented on black-beans.md
> +# Black beans with lime and coriander rice
fix'd

2017-07-28 13:54 UTC, ZooeyMiller commented
@m4v15 please re-review given the changes.

2017-07-28 14:06 UTC, m4v15 commented
@ZooeyMiller I will when there are no more conflicts.

2017-07-28 19:29 UTC, ZooeyMiller commented
@m4v15 solved merge conflicts. Please review.

2017-07-28 19:38 UTC, m4v15 approved these changes

2017-07-29 07:56 UTC, Suuuuha approved these changes

2017-07-29 08:09 UTC, matthewdking approved these changes

2017-07-29 08:10 UTC, finnhodgkin approved these changes

2017-07-29 08:11 UTC, merged