Fatoush
foundersandcoders/nazareth-recipes pull request #17
Opened 2017-07-28 14:27 UTC by Karyum

rel #16

2017-07-28 15:16 UTC, m4v15 requested changes

2017-07-28 15:16 UTC, m4v15 commented on recipes/salad/Fatoush.md
> +![Difficulty Badge](https://img.shields.io/badge/Difficulty-70%25-orange.svg)
I would agree that the reception was very positive but I think the difficulty could be lowered, 50% say? I guess the frying the bread is slightly annoying.

2017-07-28 15:16 UTC, m4v15 commented on recipes/salad/Fatoush.md
> +**First Cooked by:** @Karyum
This doesn't link to your profile like the one below

2017-07-28 16:12 UTC, Karyum commented on recipes/salad/Fatoush.md
> +![Difficulty Badge](https://img.shields.io/badge/Difficulty-70%25-orange.svg)
it's mostly because of the dressing for the salad. it's pretty hard to get the right amount

2017-07-28 16:14 UTC, Karyum commented on recipes/salad/Fatoush.md
> +**First Cooked by:** @Karyum
https://github.com/foundersandcoders/nazareth-recipes/blame/master/recipes/main/courgette_arabic_cheese_fritters.md
i used your PR as a guideline mate :smirk:

2017-07-28 16:26 UTC, finnhodgkin commented on recipes/salad/Fatoush.md
> +**First Cooked by:** @Karyum
Two wrongs don't make a right :angel:

2017-07-28 17:19 UTC, yvonne-liu commented on recipes/salad/Fatoush.md
> +**First Cooked by:** @Karyum
👯

2017-07-28 17:32 UTC, m4v15 commented on recipes/salad/Fatoush.md
> +**First Cooked by:** @Karyum
Not my fault you didn't review my code properly @Karyum

2017-07-31 15:01 UTC, Karyum commented
@m4v15 :shipit: ship it mate

2017-07-31 15:04 UTC, m4v15 approved these changes

2017-07-31 15:13 UTC, ZooeyMiller approved these changes
consistent recipe style = :tada:

2017-07-31 15:38 UTC, merged

2017-07-31 15:43 UTC, m4v15 commented
Not sure about this - did @ZooeyMiller ever try this recipe...