[WIP] Create tagine.md
foundersandcoders/nazareth-recipes pull request #21
Opened 2017-07-29 08:06 UTC by mattlub

**WIP**

still need to add the method.

**still open for comments on what's done so far.**

relates #13

2017-07-29 08:39 UTC, m4v15 commented
I'd say badges on one line looks better, but also I am now more open to people doing whatever they like with additional badges, let people have badge crazy recipe

2017-07-29 08:41 UTC, m4v15 commented on recipes/tagine.md
> +![Difficulty Badge](https://img.shields.io/badge/Difficulty-60%25-orange.svg)
We need to have a discussion on the difficulty rating

2017-07-29 08:44 UTC, m4v15 commented on recipes/tagine.md
> +![Vegan Friendly Badge](https://img.shields.io/badge/Vegan-True-brightgreen.svg)
[Honey ain't vegan pal](https://www.vegansociety.com/go-vegan/why-honey-not-vegan)

2017-07-29 08:59 UTC, Suuuuha commented on recipes/tagine.md
> +![Vegan Friendly Badge](https://img.shields.io/badge/Vegan-True-brightgreen.svg)
:open_mouth:

2017-07-29 09:06 UTC, matthewdking requested changes

2017-07-29 09:06 UTC, matthewdking commented on recipes/tagine.md
> +| head chef | Lubes |
there should be links here to profiles

2017-07-29 18:03 UTC, sofer commented on recipes/tagine.md
> +![Vegan Friendly Badge](https://img.shields.io/badge/Vegan-True-brightgreen.svg)
So, can we have a badge that allows for exploitation of bees, but not cattle? For the record, I used to be a shrimp-and-honey eating vegan on the grounds that--seriously--who really cares about anything with a brain that's smaller than a pinhead.

2017-07-29 18:05 UTC, sofer commented on recipes/tagine.md
> +![Vegan Friendly Badge](https://img.shields.io/badge/Vegan-True-brightgreen.svg)
But, seriously, I love the badges.

2017-08-01 12:17 UTC, finnhodgkin commented on recipes/tagine.md
> +![Reception Badge](https://img.shields.io/badge/Reception-Generally%20positive-green.svg)
IMHO it deserves `very positive` or at the very least `positive` :ok_hand:.

Though maybe that's just because I haven't experienced enough `very positive` Nazareth food.

2017-08-03 05:36 UTC, mattlub commented on recipes/tagine.md
> +![Difficulty Badge](https://img.shields.io/badge/Difficulty-60%25-orange.svg)
50?

2017-08-03 05:36 UTC, mattlub commented on recipes/tagine.md
> +![Difficulty Badge](https://img.shields.io/badge/Difficulty-60%25-orange.svg)
I think all difficulty ratings may be slightly inflated tbh.

2017-08-03 05:47 UTC, mattlub commented on recipes/tagine.md
> +| head chef | Lubes |
don't think they're needed, might encourage clickthroughs and lead people away from other recipes.

2017-08-03 06:37 UTC, Karyum requested changes

2017-08-03 06:37 UTC, Karyum commented on recipes/tagine.md
> +- tomato paste
how much?

2017-08-03 06:37 UTC, Karyum commented on recipes/tagine.md
> +# Lubes' Vegetable Tagine
In the README you called it Vegetable Tagine. I dont think you need your name there :grin:

2017-08-04 08:08 UTC, m4v15 approved these changes

2017-08-04 08:49 UTC, Suuuuha commented on recipes/tagine.md
> +# Lubes' Vegetable Tagine
KEEP THE NAME :1st_place_medal:

2017-08-04 08:50 UTC, Suuuuha approved these changes

2017-08-04 12:30 UTC, Karyum commented on recipes/tagine.md
> +# Lubes' Vegetable Tagine
Then ill be adding my name to the Fatoush.
and it will be " The Amaizng Mario's Fatoush " :sunglasses:

2017-08-05 09:27 UTC, mattlub commented
@Karyum @matthewdking reviews please.

2017-08-09 15:35 UTC, finnhodgkin approved these changes

2017-08-09 16:57 UTC, m4v15 commented
that last commit is brilliant. important change

2017-08-15 06:34 UTC, matthewdking approved these changes

2017-08-18 07:03 UTC, Karyum approved these changes

2017-08-18 07:04 UTC, merged