Fatoush salad
foundersandcoders/nazareth-recipes pull request #3
Opened 2017-07-16 16:24 UTC by Karyum

rel #1

2017-07-16 18:43 UTC, m4v15 requested changes
Also what do you do with the rest?

2017-07-16 18:43 UTC, m4v15 commented on Fatosuh.md
> +Combine sumac with soaking liquid, 3 tablespoons lemon juice, 2 tablespoons, garlic, 2 teaspoons vinegar, and dried mint in a small bowl. Gradually add oil, whisking constantly, until well blended. S
> 2 tablespoons, garlic

What does this mean?

2017-07-16 20:55 UTC, mattlub approved these changes

2017-07-25 20:49 UTC, mattlub commented
@Karyum I think you should add a link to your fattoush to the main README now the contents section has been added.

2017-07-26 05:18 UTC, m4v15 approved these changes

2017-07-26 05:18 UTC, merged